- platform: template
  switches:
    xbox_one:
      value_template: "{{ is_state('media_player.xbox_one', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.xbox_one
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.xbox_one

- platform: template
  switches:
    samsung_tv:
      value_template: "{{ is_state('media_player.samsung_ue65ku6000', 'on') }}"
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
          mac: xx:xx:xx:xx
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.samsung_ue65ku6000