# Sensor Notifications

# Motion Detection Notificaties / Camera
- alias: Motion detected no one home
  initial_state: 'true'
  trigger:
  - entity_id: binary_sensor.motion_bijkeuken
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_toilet
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_gang
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_office
    platform: state
    to: 'on'
  condition:
  - entity_id: group.device_status
    state: 'not_home'
    condition: state
  action:
  - service: notify.all_devices
    data_template:
      title: "Motion"
      message: >
        {% if is_state('binary_sensor.motion_bijkeuken', 'on') %}
          Er is beweging gedetecteerd in de bijkeuken terwijl er niemand thuis is! Wat wil je doen?
        {% elif is_state('binary_sensor.motion_toilet', 'on') %}
          Er is beweging gedetecteerd op het toilet terwijl er niemand thuis is! Wat wil je doen?
        {% elif is_state('binary_sensor.motion_office', 'on') %}
          Er is beweging gedetecteerd in de kleine kamer terwijl er niemand thuis is! Wat wil je doen?
        {% elif is_state('binary_sensor.motion_gang', 'on') %}
          Er is beweging gedetecteerd in de gang terwijl er niemand thuis is! Wat wil je doen?
        {% else %}
          Error
        {% endif %}
      data:
        push:
          badge: 0
          sound: default
          category: "bijkeuken_alert"

- alias: Motion detected no one home gallerij
  initial_state: 'false'
  trigger:
  - entity_id: binary_sensor.motion_gallerij_camera
    platform: state
    to: 'on'
  condition:
  - entity_id: group.device_status
    state: 'not_home'
    condition: state
  action:
  - service: notify.all_devices
    data:
      message: 'Er is beweging gedetecteerd op de gallerij! '
      title: 'Motion'
      data:
        attachment:
          content-type: jpeg
        push:
          badge: 0
          sound: default
          category: camera 
        entity_id: camera.gallerij_camera

# Smoke Detector
- alias: Smoke Alert
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_sensor
    to: 'on'
  action:
    - service: notify.all_devices
      data:
        title: "Rookmelder"
        message: "Attentie, Er is rook gesignaleerd in de Keuken, onderneem nu actie!"
        data:
          push:
            sound: "warning_smoke.wav"
            badge: 0
            category: "smoke_alert"