- platform: template
  sensors:
    motion_woonkamer_camera:
      friendly_name: Woonkamer
      device_class: motion
      value_template: "{{ is_state('input_boolean.motion_woonkamer_camera', 'on') }}"
    motion_gallerij_camera:
      friendly_name: Gallerij
      device_class: motion
      value_template: "{{ is_state('input_boolean.motion_gallerij_camera', 'on') }}"